# Generated by Django 5.2.13 on 2026-07-24 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('region', models.CharField(choices=[('Toshkent shahri', 'Toshkent shahri'), ('Toshkent viloyati', 'Toshkent viloyati'), ('Andijon', 'Andijon'), ('Buxoro', 'Buxoro'), ("Farg'ona", "Farg'ona"), ('Jizzax', 'Jizzax'), ('Xorazm', 'Xorazm'), ('Namangan', 'Namangan'), ('Navoiy', 'Navoiy'), ('Qashqadaryo', 'Qashqadaryo'), ("Qoraqalpog'iston", "Qoraqalpog'iston"), ('Samarqand', 'Samarqand'), ('Sirdaryo', 'Sirdaryo'), ('Surxondaryo', 'Surxondaryo')], default='Toshkent shahri', max_length=40, verbose_name='Hudud')),
                ('specialty', models.CharField(blank=True, max_length=80, verbose_name='Mutaxassislik')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('bio', models.TextField(blank=True, verbose_name='Qisqacha')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Reyting bali')),
                ('one_id_verified', models.BooleanField(default=False, verbose_name='ONE ID tasdiqlangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profillar',
                'ordering': ['-score'],
            },
        ),
    ]
