# Generated by Django 5.2.13 on 2026-07-24 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Nomi')),
                ('kind', models.CharField(choices=[('skill', "Ko'nikma baholash"), ('psych', 'Psixologik test')], default='skill', max_length=5, verbose_name='Turi')),
                ('icon', models.CharField(choices=[('code', 'Kod'), ('analytics', 'Tahlil'), ('language', 'Til'), ('design', 'Dizayn'), ('management', 'Boshqaruv'), ('brain', 'Aql'), ('emotion', 'Hissiyot'), ('stress', 'Stress'), ('leadership', 'Yetakchilik'), ('motivation', 'Motivatsiya')], default='code', max_length=12, verbose_name='Belgi')),
                ('color', models.CharField(choices=[('blue', "Ko'k"), ('orange', "To'q sariq"), ('dark', 'Qora'), ('green', 'Yashil'), ('purple', 'Binafsha'), ('teal', 'Moviy-yashil'), ('red', 'Qizil'), ('indigo', 'Indigo')], default='blue', max_length=10, verbose_name='Rang')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=15, verbose_name='Davomiyligi (daqiqa)')),
                ('level', models.CharField(choices=[("Boshlang'ich", "Boshlang'ich"), ("O'rta", "O'rta"), ('Yuqori', 'Yuqori'), ('Umumiy', 'Umumiy')], default='Umumiy', max_length=15, verbose_name='Daraja')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Savol')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.assessment', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250, verbose_name='Javob')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri javob")),
                ('weight', models.PositiveSmallIntegerField(default=0, verbose_name='Ball (psixologik test uchun)')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='assessments.question', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Javob varianti',
                'verbose_name_plural': 'Javob variantlari',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, verbose_name='Natija (%)')),
                ('correct_answers', models.PositiveSmallIntegerField(default=0, verbose_name="To'g'ri javoblar")),
                ('total_questions', models.PositiveSmallIntegerField(default=0, verbose_name='Jami savollar')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Yakunlangan')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assessments.assessment', verbose_name='Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Test natijasi',
                'verbose_name_plural': 'Test natijalari',
                'ordering': ['-completed_at'],
            },
        ),
    ]
