# Generated by Django 5.2.13 on 2026-07-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Sarlavha')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Qisqacha')),
                ('image_url', models.URLField(blank=True, verbose_name='Rasm (URL)')),
                ('link', models.CharField(blank=True, max_length=200, verbose_name='Havola')),
                ('color', models.CharField(choices=[('blue', "Ko'k"), ('orange', "To'q sariq"), ('dark', 'Qora'), ('green', 'Yashil'), ('purple', 'Binafsha'), ('teal', 'Moviy-yashil'), ('red', 'Qizil'), ('indigo', 'Indigo')], default='blue', max_length=10, verbose_name='Rang')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannerlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('body', models.TextField(blank=True, verbose_name='Matn')),
                ('category', models.CharField(choices=[("E'lon", "E'lon"), ('Yangilik', 'Yangilik'), ('Yangilanish', 'Yangilanish'), ('Tadbir', 'Tadbir'), ('Kurs', 'Kurs')], default='Yangilik', max_length=20, verbose_name='Turkum')),
                ('card_color', models.CharField(choices=[('blue', "Ko'k"), ('orange', "To'q sariq"), ('dark', 'Qora'), ('green', 'Yashil'), ('purple', 'Binafsha'), ('teal', 'Moviy-yashil'), ('red', 'Qizil'), ('indigo', 'Indigo')], default='blue', max_length=10, verbose_name='Karta rangi')),
                ('image_url', models.URLField(blank=True, verbose_name='Rasm (URL)')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Muhim')),
                ('is_published', models.BooleanField(default=True, verbose_name='Chop etilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-created_at'],
            },
        ),
    ]
