# Generated by Django 5.2.13 on 2026-07-24 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=120, verbose_name='Kompaniya')),
                ('position', models.CharField(max_length=120, verbose_name='Lavozim')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('location', models.CharField(max_length=120, verbose_name='Manzil')),
                ('salary_min', models.PositiveIntegerField(default=0, verbose_name='Maosh (min)')),
                ('salary_max', models.PositiveIntegerField(default=0, verbose_name='Maosh (max)')),
                ('currency', models.CharField(choices=[('UZS', "so'm"), ('USD', 'USD')], default='UZS', max_length=3, verbose_name='Valyuta')),
                ('work_type', models.CharField(choices=[('Ofisda', 'Ofisda'), ('Gibrid', 'Gibrid'), ('Masofaviy', 'Masofaviy')], default='Ofisda', max_length=12, verbose_name='Ish turi')),
                ('field', models.CharField(choices=[('IT', 'IT'), ('Moliya', 'Moliya'), ('Marketing', 'Marketing'), ("Ta'lim", "Ta'lim"), ('Sanoat', 'Sanoat'), ('Telekommunikatsiya', 'Telekommunikatsiya'), ('Huquq', 'Huquq'), ('Boshqaruv', 'Boshqaruv')], default='IT', max_length=30, verbose_name='Soha')),
                ('card_color', models.CharField(choices=[('blue', "Ko'k"), ('orange', "To'q sariq"), ('dark', 'Qora'), ('green', 'Yashil'), ('purple', 'Binafsha'), ('teal', 'Moviy-yashil'), ('red', 'Qizil'), ('indigo', 'Indigo')], default='blue', max_length=10, verbose_name='Karta rangi')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Shoshilinch')),
                ('logo_url', models.URLField(blank=True, verbose_name='Logo (URL)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Vakansiya',
                'verbose_name_plural': 'Vakansiyalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Xat')),
                ('status', models.CharField(choices=[('pending', "Ko'rib chiqilmoqda"), ('reviewing', 'Suhbat bosqichida'), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi')], default='pending', max_length=12, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='vacancies.vacancy', verbose_name='Vakansiya')),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'vacancy')},
            },
        ),
    ]
