# Generated by Django 5.2.13 on 2026-07-24 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Nomi')),
                ('icon', models.CharField(default='trending', max_length=20, verbose_name='Belgi')),
                ('color', models.CharField(choices=[('blue', "Ko'k"), ('orange', "To'q sariq"), ('dark', 'Qora'), ('green', 'Yashil'), ('purple', 'Binafsha'), ('teal', 'Moviy-yashil'), ('red', 'Qizil'), ('indigo', 'Indigo')], default='blue', max_length=10, verbose_name='Rang')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'KPI turkumi',
                'verbose_name_plural': 'KPI turkumlari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='KpiItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name="Ko'rsatkich")),
                ('value', models.FloatField(default=0, verbose_name='Qiymat')),
                ('target', models.FloatField(default=100, verbose_name='Maqsad')),
                ('unit', models.CharField(default='%', max_length=10, verbose_name="O'lchov birligi")),
                ('trend', models.FloatField(default=0, verbose_name="O'zgarish")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='performance.kpicategory', verbose_name='Turkum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_items', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "KPI ko'rsatkichi",
                'verbose_name_plural': "KPI ko'rsatkichlari",
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='Kelish vaqti')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='Ketish vaqti')),
                ('method', models.CharField(choices=[('gps', 'GPS'), ('qr', 'QR kod')], default='gps', max_length=3, verbose_name='Usul')),
                ('status', models.CharField(choices=[('present', 'Ishda'), ('late', 'Kechikkan'), ('absent', 'Kelmagan')], default='present', max_length=8, verbose_name='Holat')),
                ('location_name', models.CharField(blank=True, max_length=160, verbose_name='Joylashuv')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Kenglik')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Uzunlik')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Davomat yozuvi',
                'verbose_name_plural': 'Davomat yozuvlari',
                'ordering': ['-date'],
                'unique_together': {('user', 'date', 'method')},
            },
        ),
    ]
